### ISSUE TITLE
There is no database schema !!

### ISSUE THREAD

**Issue by spatsatzis** [Eye4web/ZfcUserSettings#2]
Hello , there is no data folder neither database schema !! It only has 2 xml of doctrine scripts !!

How im supposed to do step 4 ??
1. Create database schema(see data folder for dumps)

thanks

**Comment by Danielss89** [comment]
Whoops, my mistake, forgot to make those. Are you using doctrine?

**Comment by spatsatzis** [comment]
Nop , im not :) 

No problem but i wanted to inform you :)

**Comment by Danielss89** [comment]
Ok, thx. This module doesn't have a ZendDB adapter yet(PR's welcome), so you can't use the module without doctrine, and doctrine can generate the database schema itself.
